// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDURZfJp_tUABcmmEecyyZPDH7gELi-Yp4',
    appId: '1:493710933606:web:538fa9363af61118ccb7a7',
    messagingSenderId: '493710933606',
    projectId: 'car-park-b9d1c',
    authDomain: 'car-park-b9d1c.firebaseapp.com',
    databaseURL: 'https://car-park-b9d1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-park-b9d1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcLbmTED0JtLTNSXq-C01KWiDXGqwQv0',
    appId: '1:493710933606:android:ce7c4a31ee0d40a9ccb7a7',
    messagingSenderId: '493710933606',
    projectId: 'car-park-b9d1c',
    databaseURL: 'https://car-park-b9d1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-park-b9d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxRos2EFx1RtOPAnNwn4_7bHjBexqWnA',
    appId: '1:493710933606:ios:1a20c23686bf1275ccb7a7',
    messagingSenderId: '493710933606',
    projectId: 'car-park-b9d1c',
    databaseURL: 'https://car-park-b9d1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-park-b9d1c.firebasestorage.app',
    androidClientId: '493710933606-n3dn1rfca3487ijchjnb9rmjdgj0k2ud.apps.googleusercontent.com',
    iosClientId: '493710933606-6tvdj5q61p1vl792lb0s6sdj19sstv2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.carParking',
  );
}
